# Generated by Django 5.0.6 on 2024-06-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=60)),
                ('category', models.CharField(max_length=60)),
                ('image', models.FileField(max_length=200, null=True, upload_to='carousels/')),
            ],
        ),
    ]
